In [31]:
import pandas as pd
import numpy as np
import geopandas as gpd

### Top 5 at risk for past 5 years

In [36]:
risk = pd.read_csv(r'/Users/saurabhlevin/Deployment/IDS-DRR-Himachal-Pradesh-Risk-Score-Model/RiskScoreModel/data/risk_score_final_district.csv')
risk_dist = risk.loc[risk['tehsil'].isnull()]
dist_risk = risk_dist.groupby('district').agg({'topsis-score':'mean'}
                                              ).reset_index()
dist_risk_sort = dist_risk.sort_values(by='topsis-score', ascending=False)
dist_risk_sort

          district  topsis-score
0         BILASPUR      0.727492
2         HAMIRPUR      0.696132
9          SIRMAUR      0.695941
7            MANDI      0.680467
11             UNA      0.678265
3           KANGRA      0.647490
1           CHAMBA      0.632467
10           SOLAN      0.585276
8           SHIMLA      0.551444
5            KULLU      0.494738
6   LAHAUL & SPITI      0.372129
4          KINNAUR      0.269778

In [ ]:
key_districts = ['MANDI', 'KULLU', 'KANGRA', 'SHIMLA', 'SIRMAUR']
focus_risk = risk_dist.loc[risk_dist['district'].isin(key_districts)]
for n in key_districts:
    a = risk_dist.loc[risk_dist['district']==n].agg({'exposure':'mean'})
    b = risk_dist.loc[risk_dist['district']==n].agg({'flood-hazard':'mean'})
    c = risk_dist.loc[risk_dist['district']==n].agg({'vulnerability':'mean'})
    d = risk_dist.loc[risk_dist['district']==n].agg({'government-response':'mean'})
    print(n , '=' , a,b,c,d)
    df = focus_risk.groupby('district').agg({
        'exposure': 'mean',
        'flood-hazard': 'mean',
        'vulnerability': 'mean',
        'government-response': 'mean'
    }).reset_index()

MANDI = exposure    3.0
dtype: float64 flood-hazard    3.078431
dtype: float64 vulnerability    4.0
dtype: float64 government-response    1.745098
dtype: float64
KULLU = exposure    2.0
dtype: float64 flood-hazard    1.509804
dtype: float64 vulnerability    2.960784
dtype: float64 government-response    2.45098
dtype: float64
KANGRA = exposure    4.0
dtype: float64 flood-hazard    4.27451
dtype: float64 vulnerability    2.333333
dtype: float64 government-response    1.823529
dtype: float64
SHIMLA = exposure    2.098039
dtype: float64 flood-hazard    2.215686
dtype: float64 vulnerability    1.960784
dtype: float64 government-response    1.823529
dtype: float64
SIRMAUR = exposure    1.411765
dtype: float64 flood-hazard    3.588235
dtype: float64 vulnerability    4.647059
dtype: float64 government-response    2.745098
dtype: float64

In [26]:
import numpy as np
import pandas as pd

risk = pd.read_csv(r'/Users/saurabhlevin/Deployment/IDS-DRR-Himachal-Pradesh-Risk-Score-Model/RiskScoreModel/data/risk_score_final_district.csv')

# Use only subdistrict (tehsil) rows
tehsil_rows = risk[risk['tehsil'].notna()].copy()

# Option A: use the latest month in the data
latest = tehsil_rows['timeperiod'].max()
risk_latest = tehsil_rows[tehsil_rows['timeperiod'] == latest].copy()

# Population-weighted mean exposure per district
district_exposure_rank = (
    risk_latest.groupby('district')
    .apply(lambda g: np.average(g['exposure'], weights=g['sum-population']))  # note the hyphenated column name
    .sort_values(ascending=False)
)

print(district_exposure_rank)

district
UNA               4.730349
BILASPUR          4.396648
SOLAN             4.240827
KANGRA            4.135488
CHAMBA            3.995877
MANDI             3.882398
HAMIRPUR          3.616337
SHIMLA            3.608217
KULLU             3.559248
SIRMAUR           3.312738
KINNAUR           1.328868
LAHAUL & SPITI    1.000000
dtype: float64

/var/folders/mn/tyjcr2q91wz11fzw0ttcj3780000gn/T/ipykernel_80747/2091898529.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: np.average(g['exposure'], weights=g['sum-population']))  # note the hyphenated column name

In [27]:
for n in dist_risk_sort['district']:
    a = risk_dist.loc[risk_dist['district']==n].agg({'exposure':'mean'})
    b = risk_dist.loc[risk_dist['district']==n].agg({'flood-hazard':'mean'})
    c = risk_dist.loc[risk_dist['district']==n].agg({'vulnerability':'mean'})
    d = risk_dist.loc[risk_dist['district']==n].agg({'government-response':'mean'})
    print(n , '=' , a,b,c,d)
    df = risk_dist.groupby('district').agg({
        'exposure': 'mean',
        'flood-hazard': 'mean',
        'vulnerability': 'mean',
        'government-response': 'mean'
    }).reset_index()
df

BILASPUR = exposure    4.352941
dtype: float64 flood-hazard    3.686275
dtype: float64 vulnerability    3.843137
dtype: float64 government-response    2.921569
dtype: float64
HAMIRPUR = exposure    3.0
dtype: float64 flood-hazard    3.54902
dtype: float64 vulnerability    3.196078
dtype: float64 government-response    2.078431
dtype: float64
SIRMAUR = exposure    1.411765
dtype: float64 flood-hazard    3.588235
dtype: float64 vulnerability    4.647059
dtype: float64 government-response    2.745098
dtype: float64
MANDI = exposure    3.0
dtype: float64 flood-hazard    3.078431
dtype: float64 vulnerability    4.0
dtype: float64 government-response    1.745098
dtype: float64
UNA = exposure    5.0
dtype: float64 flood-hazard    4.0
dtype: float64 vulnerability    2.078431
dtype: float64 government-response    2.686275
dtype: float64
KANGRA = exposure    4.0
dtype: float64 flood-hazard    4.27451
dtype: float64 vulnerability    2.333333
dtype: float64 government-response    1.823529
dtype: float64
CHAMBA = exposure    3.588235
dtype: float64 flood-hazard    2.098039
dtype: float64 vulnerability    3.901961
dtype: float64 government-response    2.333333
dtype: float64
SOLAN = exposure    5.0
dtype: float64 flood-hazard    3.823529
dtype: float64 vulnerability    1.215686
dtype: float64 government-response    2.019608
dtype: float64
SHIMLA = exposure    2.098039
dtype: float64 flood-hazard    2.215686
dtype: float64 vulnerability    1.960784
dtype: float64 government-response    1.823529
dtype: float64
KULLU = exposure    2.0
dtype: float64 flood-hazard    1.509804
dtype: float64 vulnerability    2.960784
dtype: float64 government-response    2.45098
dtype: float64
LAHAUL & SPITI = exposure    1.0
dtype: float64 flood-hazard    1.0
dtype: float64 vulnerability    4.784314
dtype: float64 government-response    3.0
dtype: float64
KINNAUR = exposure    1.0
dtype: float64 flood-hazard    1.019608
dtype: float64 vulnerability    1.0
dtype: float64 government-response    2.764706
dtype: float64

          district  exposure  flood-hazard  vulnerability  government-response
0         BILASPUR  4.352941      3.686275       3.843137             2.921569
1           CHAMBA  3.588235      2.098039       3.901961             2.333333
2         HAMIRPUR  3.000000      3.549020       3.196078             2.078431
3           KANGRA  4.000000      4.274510       2.333333             1.823529
4          KINNAUR  1.000000      1.019608       1.000000             2.764706
5            KULLU  2.000000      1.509804       2.960784             2.450980
6   LAHAUL & SPITI  1.000000      1.000000       4.784314             3.000000
7            MANDI  3.000000      3.078431       4.000000             1.745098
8           SHIMLA  2.098039      2.215686       1.960784             1.823529
9          SIRMAUR  1.411765      3.588235       4.647059             2.745098
10           SOLAN  5.000000      3.823529       1.215686             2.019608
11             UNA  5.000000      4.000000       2.078431             2.686275

In [4]:
indicator = 'flood-hazard'
indicator_top = risk_dist.groupby('district').agg({indicator:'mean'}).reset_index()
indicator_top = indicator_top.sort_values(by=indicator, ascending=False)
indicator_top

          district  flood-hazard
3           KANGRA      4.466667
11             UNA      4.377778
10           SOLAN      4.266667
9          SIRMAUR      4.244444
0         BILASPUR      4.222222
2         HAMIRPUR      4.177778
7            MANDI      4.022222
1           CHAMBA      3.488889
8           SHIMLA      3.355556
5            KULLU      2.466667
4          KINNAUR      1.044444
6   LAHAUL & SPITI      1.000000

In [5]:
# monsoon 
monsoon = risk_dist[risk_dist['timeperiod'].str.split('_').str[1].isin(['06', '07', '08', '09'])]
monsoon_risk = monsoon.groupby('district').agg({'topsis-score':'mean'}).reset_index()
monsoon_risk_sort = monsoon_risk.sort_values(by='topsis-score', ascending=False)
monsoon_risk_csv = []
for m in monsoon_risk_sort['district']:
    a = monsoon.loc[monsoon['district']==m].agg({'exposure':'mean'})
    b = monsoon.loc[monsoon['district']==m].agg({'flood-hazard':'mean'})
    c = monsoon.loc[monsoon['district']==m].agg({'vulnerability':'mean'})
    d = monsoon.loc[monsoon['district']==m].agg({'government-response':'mean'})
    e = monsoon.loc[monsoon['district']==m].agg({'topsis-score':'mean'})

    #e = monsoon.loc[monsoon['district']==m].agg({'landd-score':'mean'})
    #print(m , '=' , a,b,c,d)#,e)
    monsoon_risk_csv.append([m, a.values[0], b.values[0], c.values[0], d.values[0]])#, e.values[0]])
monsoon_risk_csv#.to_csv(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\Deployment\IDS-DRR-Assam-Risk-Model\RiskScoreModel\data\monsoon_risk_district.csv', index=False)
monsoon_risk_csv = pd.DataFrame(monsoon_risk_csv, columns=['district', 'exposure', 'flood-hazard', 'vulnerability', 'government-response'])
monsoon_risk_csv#.to_csv(r'D:\CivicDataLab_IDS-DRR\ASDMA Meetings\Pre-monsoon-2025_SDRF\monsoon_risk_district.csv', index=False)

          district  exposure  flood-hazard  vulnerability  government-response
0              UNA       5.0        4.5625         2.9375               4.8750
1          SIRMAUR       2.0        4.5000         4.3750               5.0000
2         BILASPUR       3.0        4.3125         3.3750               4.8750
3         HAMIRPUR       1.0        4.3750         3.6875               5.0000
4           KANGRA       3.0        4.8125         2.9375               3.1875
5            SOLAN       4.0        4.5000         2.8750               4.5000
6            MANDI       2.0        4.0625         4.1250               2.7500
7           CHAMBA       4.0        3.0625         4.1250               4.8750
8           SHIMLA       3.0        3.2500         3.7500               3.7500
9            KULLU       2.0        2.0625         2.9375               4.8750
10         KINNAUR       1.0        1.0000         3.1875               5.0000
11  LAHAUL & SPITI       1.0        1.0000         3.1250               5.0000

In [5]:
for n in monsoon_risk_csv['district'].head(5):
    a = monsoon_risk_csv.loc[monsoon_risk_csv['district']==n].agg({'exposure':'mean'})
    b = monsoon_risk_csv.loc[monsoon_risk_csv['district']==n].agg({'flood-hazard':'mean'})
    c = monsoon_risk_csv.loc[monsoon_risk_csv['district']==n].agg({'vulnerability':'mean'})
    d = monsoon_risk_csv.loc[monsoon_risk_csv['district']==n].agg({'government-response':'mean'})
    print(n , '=' , a,b,c,d)
    df = monsoon_risk_csv.groupby('district').agg({
        'exposure': 'mean',
        'flood-hazard': 'mean',
        'vulnerability': 'mean',
        'government-response': 'mean'
    }).reset_index()
df

UNA = exposure    5.0
dtype: float64 flood-hazard    4.6
dtype: float64 vulnerability    2.333333
dtype: float64 government-response    4.2
dtype: float64
BILASPUR = exposure    3.0
dtype: float64 flood-hazard    4.333333
dtype: float64 vulnerability    2.933333
dtype: float64 government-response    5.0
dtype: float64
KANGRA = exposure    3.0
dtype: float64 flood-hazard    4.8
dtype: float64 vulnerability    2.2
dtype: float64 government-response    4.8
dtype: float64
SIRMAUR = exposure    2.0
dtype: float64 flood-hazard    4.466667
dtype: float64 vulnerability    3.0
dtype: float64 government-response    4.466667
dtype: float64
HAMIRPUR = exposure    1.0
dtype: float64 flood-hazard    4.4
dtype: float64 vulnerability    2.2
dtype: float64 government-response    4.066667
dtype: float64

   district  exposure  flood-hazard  vulnerability  government-response
0  BILASPUR       3.0      4.333333       2.933333             5.000000
1  HAMIRPUR       1.0      4.400000       2.200000             4.066667
2    KANGRA       3.0      4.800000       2.200000             4.800000
3   SIRMAUR       2.0      4.466667       3.000000             4.466667
4       UNA       5.0      4.600000       2.333333             4.200000

### Hazard

In [43]:
haz = pd.read_csv(r'/Users/saurabhlevin/Deployment/IDS-DRR-Himachal-Pradesh-Risk-Score-Model/RiskScoreModel/data/factor_scores_l1_flood-hazard.csv')
#vul_monsoon = vul.loc[vul['timeperiod'].str.split('_').str[1].isin(['06', '07', '08', '09'])]
#vul_ranking = vul_monsoon.groupby('district').agg({'landd_score':'sum'}).reset_index()
haz_ranking = haz.groupby('district').agg({'flood-hazard':'mean'}).reset_index()
haz_ranking = haz_ranking.sort_values(by='flood-hazard', ascending=False)
for m in haz_ranking['district']:#.head(10):
    a = haz.loc[haz['district']==m].agg({'flood-hazard':'mean'})
    b = risk_dist.loc[risk_dist['district']==m].agg({'sum-rain':'mean'})
   #c = haz.loc[haz['district']==m].agg({'flood-hazard':'mean'})
    #d = risk_dist.loc[risk_dist['district']==m].agg({'government-response':'mean'})
    #print(m , '=' , a,b,c,d)
    print(m , '=' , a,b)

UNA = flood-hazard    4.25098
dtype: float64 sum-rain    207.213922
dtype: float64
KANGRA = flood-hazard    4.229055
dtype: float64 sum-rain    1256.45902
dtype: float64
BILASPUR = flood-hazard    4.163399
dtype: float64 sum-rain    182.010784
dtype: float64
HAMIRPUR = flood-hazard    4.151961
dtype: float64 sum-rain    202.731765
dtype: float64
SOLAN = flood-hazard    4.110294
dtype: float64 sum-rain    330.752941
dtype: float64
SIRMAUR = flood-hazard    4.013725
dtype: float64 sum-rain    552.333725
dtype: float64
MANDI = flood-hazard    3.905637
dtype: float64 sum-rain    666.34549
dtype: float64
CHAMBA = flood-hazard    3.372549
dtype: float64 sum-rain    1095.000196
dtype: float64
SHIMLA = flood-hazard    3.319328
dtype: float64 sum-rain    689.561176
dtype: float64
KULLU = flood-hazard    2.619048
dtype: float64 sum-rain    782.724118
dtype: float64
KINNAUR = flood-hazard    1.571895
dtype: float64 sum-rain    448.196078
dtype: float64
LAHAUL & SPITI = flood-hazard    1.127451
dtype: float64 sum-rain    1274.678627
dtype: float64

### Exposure

In [44]:
exp = pd.read_csv(r'/Users/saurabhlevin/Deployment/IDS-DRR-Himachal-Pradesh-Risk-Score-Model/RiskScoreModel/data/factor_scores_l1_exposure.csv')
#vul_monsoon = vul.loc[vul['timeperiod'].str.split('_').str[1].isin(['06', '07', '08', '09'])]
#vul_ranking = vul_monsoon.groupby('district').agg({'landd_score':'sum'}).reset_index()
exp_ranking = exp.groupby('district').agg({'exposure':'sum'}).reset_index()
exp_ranking = exp_ranking.sort_values(by='exposure', ascending=False)
for m in exp_ranking['district']:#.head(10):
    a = exp.loc[exp['district']==m].agg({'exposure':'sum'})
    #b = risk_dist.loc[risk_dist['district']==m].agg({'flood-hazard':'mean'})
    c = exp.loc[exp['district']==m].agg({'exposure':'sum'})
    #d = risk_dist.loc[risk_dist['district']==m].agg({'government-response':'mean'})
    #print(m , '=' , a,b,c,d)
    print(m , '=' , a,c)

KANGRA = exposure    3570
dtype: int64 exposure    3570
dtype: int64
MANDI = exposure    2532
dtype: int64 exposure    2532
dtype: int64
SHIMLA = exposure    1887
dtype: int64 exposure    1887
dtype: int64
SOLAN = exposure    1428
dtype: int64 exposure    1428
dtype: int64
CHAMBA = exposure    1275
dtype: int64 exposure    1275
dtype: int64
HAMIRPUR = exposure    1275
dtype: int64 exposure    1275
dtype: int64
BILASPUR = exposure    1242
dtype: int64 exposure    1242
dtype: int64
SIRMAUR = exposure    1224
dtype: int64 exposure    1224
dtype: int64
UNA = exposure    1173
dtype: int64 exposure    1173
dtype: int64
KULLU = exposure    1071
dtype: int64 exposure    1071
dtype: int64
KINNAUR = exposure    357
dtype: int64 exposure    357
dtype: int64
LAHAUL & SPITI = exposure    102
dtype: int64 exposure    102
dtype: int64

In [47]:

# 1) Sum tehsils -> district-month
exp_dm = (exp.groupby(['district','timeperiod'], as_index=False)['exposure'].mean())

# 2) Choose your aggregation target
# a) Total exposure over all months (same as your accurate SUM ranking)
exp_sum = (exp_dm.groupby('district', as_index=False)['exposure'].sum()
                  .sort_values('exposure', ascending=False))

# b) Average monthly exposure (fair “mean”)
exp_mean_monthly = (exp_dm.groupby('district', as_index=False)['exposure'].mean()
                           .sort_values('exposure', ascending=False))

In [48]:
exp_mean_monthly

          district  exposure
11             UNA  4.600000
0         BILASPUR  4.058824
10           SOLAN  3.500000
3           KANGRA  3.181818
1           CHAMBA  3.125000
2         HAMIRPUR  3.125000
7            MANDI  3.102941
5            KULLU  3.000000
8           SHIMLA  2.642857
9          SIRMAUR  2.400000
4          KINNAUR  1.166667
6   LAHAUL & SPITI  1.000000

### Vulnerability score

In [4]:
import numpy as np

In [49]:
vul = pd.read_csv(r'/Users/saurabhlevin/Deployment/IDS-DRR-Himachal-Pradesh-Risk-Score-Model/RiskScoreModel/data/factor_scores_l1_vulnerability.csv')
#vul_monsoon = vul.loc[vul['timeperiod'].str.split('_').str[1].isin(['06', '07', '08', '09'])]
#vul_ranking = vul_monsoon.groupby('district').agg({'landd_score':'sum'}).reset_index()
vul_ranking = vul.groupby('district').agg({'vulnerability':'sum'}).reset_index()
vul_ranking = vul_ranking.sort_values(by='vulnerability', ascending=False)
for m in vul_ranking['district']:#.head(10):
    a = vul.loc[vul['district']==m].agg({'landd_score':'sum'})
    #b = risk_dist.loc[risk_dist['district']==m].agg({'flood-hazard':'mean'})
    c = vul.loc[vul['district']==m].agg({'vulnerability':'mean'})
    #d = risk_dist.loc[risk_dist['district']==m].agg({'government-response':'mean'})
    #print(m , '=' , a,b,c,d)
    print(m , '=' , a,c)

MANDI = landd_score    823.009679
dtype: float64 vulnerability    3.568627
dtype: float64
KANGRA = landd_score    1125.373813
dtype: float64 vulnerability    2.434938
dtype: float64
SHIMLA = landd_score    717.591525
dtype: float64 vulnerability    2.57563
dtype: float64
SIRMAUR = landd_score    513.505628
dtype: float64 vulnerability    3.37451
dtype: float64
CHAMBA = landd_score    408.992104
dtype: float64 vulnerability    3.617647
dtype: float64
HAMIRPUR = landd_score    409.028438
dtype: float64 vulnerability    2.985294
dtype: float64
KULLU = landd_score    363.848436
dtype: float64 vulnerability    2.896359
dtype: float64
BILASPUR = landd_score    311.466626
dtype: float64 vulnerability    3.137255
dtype: float64
UNA = landd_score    256.059416
dtype: float64 vulnerability    2.380392
dtype: float64
SOLAN = landd_score    408.64714
dtype: float64 vulnerability    1.406863
dtype: float64
LAHAUL & SPITI = landd_score    102.0
dtype: float64 vulnerability    3.823529
dtype: float64
KINNAUR = landd_score    308.87033
dtype: float64 vulnerability    1.03268
dtype: float64

In [50]:
vul = pd.read_csv(r'/Users/saurabhlevin/Deployment/IDS-DRR-Himachal-Pradesh-Risk-Score-Model/RiskScoreModel/data/factor_scores_l1_vulnerability.csv')
#vul_monsoon = vul.loc[vul['timeperiod'].str.split('_').str[1].isin(['06', '07', '08', '09'])]
#vul_ranking = vul_monsoon.groupby('district').agg({'landd_score':'sum'}).reset_index()
vul_ranking = vul.groupby('district').agg({'landd_score':'sum'}).reset_index()
vul_ranking = vul_ranking.sort_values(by='landd_score', ascending=False)
for m in vul_ranking['district']:#.head(10):
    a = vul.loc[vul['district']==m].agg({'landd_score':'sum'})
    #b = risk_dist.loc[risk_dist['district']==m].agg({'flood-hazard':'mean'})
    c = vul.loc[vul['district']==m].agg({'vulnerability':'mean'})
    #d = risk_dist.loc[risk_dist['district']==m].agg({'government-response':'mean'})
    #print(m , '=' , a,b,c,d)
    print(m , '=' , a,c)

KANGRA = landd_score    1125.373813
dtype: float64 vulnerability    2.434938
dtype: float64
MANDI = landd_score    823.009679
dtype: float64 vulnerability    3.568627
dtype: float64
SHIMLA = landd_score    717.591525
dtype: float64 vulnerability    2.57563
dtype: float64
SIRMAUR = landd_score    513.505628
dtype: float64 vulnerability    3.37451
dtype: float64
HAMIRPUR = landd_score    409.028438
dtype: float64 vulnerability    2.985294
dtype: float64
CHAMBA = landd_score    408.992104
dtype: float64 vulnerability    3.617647
dtype: float64
SOLAN = landd_score    408.64714
dtype: float64 vulnerability    1.406863
dtype: float64
KULLU = landd_score    363.848436
dtype: float64 vulnerability    2.896359
dtype: float64
BILASPUR = landd_score    311.466626
dtype: float64 vulnerability    3.137255
dtype: float64
KINNAUR = landd_score    308.87033
dtype: float64 vulnerability    1.03268
dtype: float64
UNA = landd_score    256.059416
dtype: float64 vulnerability    2.380392
dtype: float64
LAHAUL & SPITI = landd_score    102.0
dtype: float64 vulnerability    3.823529
dtype: float64

In [17]:
# Aggregate vulnerability by district from risk_dist
vul_by_district = vul.groupby(['district','timeperiod'], as_index=False)['efficiency'].mean()
landd_by_district = vul.groupby(['district','timeperiod'], as_index=False)['landd_score'].mean()
merged_vul = vul_by_district.merge(landd_by_district, on=['district', 'timeperiod'], how='left')

# Merge with vul_ranking which contains landd_score by district

# Calculate the correlation between landd_score and vulnerability
corr = merged_vul['landd_score'].corr(merged_vul['efficiency'])
print("Correlation between landd_score and efficiency:", corr)

Correlation between landd_score and efficiency: -0.32269773875821484

In [10]:
# Highest and lowest funding received
risk_dist['total-funds'] = risk_dist['relief-and-mitigation-sanction-value'] + risk_dist['total-tender-awarded-value']#
#dist_response = risk_dist.groupby('district').agg({'total-funds':'sum'})
dist_response = risk_dist.groupby('district').agg({'government-response':'mean'}).reset_index()
dist_response_sort = dist_response.sort_values(by='government-response', ascending=True)
dist_response_sort

C:\Users\saura\AppData\Local\Temp\ipykernel_33648\374607718.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  risk_dist['total-funds'] = risk_dist['relief-and-mitigation-sanction-value'] + risk_dist['total-tender-awarded-value']#

          district  government-response
7            MANDI             2.733333
3           KANGRA             3.111111
8           SHIMLA             3.711111
10           SOLAN             4.422222
5            KULLU             4.688889
11             UNA             4.911111
0         BILASPUR             4.955556
1           CHAMBA             4.955556
2         HAMIRPUR             4.977778
9          SIRMAUR             4.977778
4          KINNAUR             5.000000
6   LAHAUL & SPITI             5.000000

In [45]:
# Highest and lowest funding received
risk_dist['total-funds'] = risk_dist['total-expenditure-value'] + risk_dist['total-tender-awarded-value']
dist_response = risk_dist.groupby('district').agg({'total-funds':'sum'})
#dist_response = risk_dist.groupby('district').agg({'government-response':'mean'}).reset_index()
dist_response_sort = dist_response.sort_values(by='total-funds')#, ascending=False)
dist_response_sort

C:\Users\saura\AppData\Local\Temp\ipykernel_49156\3438842923.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  risk_dist['total-funds'] = risk_dist['total-expenditure-value'] + risk_dist['total-tender-awarded-value']

                          total-funds
district
SIVASAGAR                0.000000e+00
KARBI ANGLONG            0.000000e+00
DIMA HASAO               6.270000e+06
BONGAIGAON               1.994961e+07
BAJALI                   1.518096e+08
WEST KARBI ANGLONG       1.552178e+08
HOJAI                    1.716333e+08
SOUTH SALMARA MANCACHAR  1.997388e+08
CHARAIDEO                2.293453e+08
GOLAGHAT                 4.345440e+08
BAKSA                    6.378759e+08
JORHAT                   7.077554e+08
GOALPARA                 9.347072e+08
KAMRUP                   9.535317e+08
DHUBRI                   9.856004e+08
TINSUKIA                 1.008941e+09
HAILAKANDI               1.039149e+09
UDALGURI                 1.058288e+09
TAMULPUR                 1.170672e+09
CACHAR                   1.206031e+09
SONITPUR                 1.238109e+09
LAKHIMPUR                1.263521e+09
NALBARI                  1.366067e+09
BISWANATH                1.432814e+09
KARIMGANJ                1.453828e+09
CHIRANG                  1.464378e+09
MAJULI                   1.645225e+09
KOKRAJHAR                1.712217e+09
BARPETA                  1.747132e+09
DARRANG                  1.788093e+09
DHEMAJI                  2.252893e+09
NAGAON                   2.744872e+09
DIBRUGARH                3.541115e+09
MORIGAON                 4.104739e+09
KAMRUP METRO             5.222973e+09

In [19]:
dist_sdrf = risk_dist.groupby('district').agg({'total-expenditure-value':'sum'})
#dist_response = risk_dist.groupby('district').agg({'government-response':'mean'}).reset_index()
dist_sdrf_sort = dist_sdrf.sort_values(by='total-expenditure-value')#, ascending=False)
dist_sdrf_sort

                         total-expenditure-value
district
BAJALI                                       0.0
TAMULPUR                                     0.0
SIVASAGAR                                    0.0
LAKHIMPUR                                    0.0
KARBI ANGLONG                                0.0
DIMA HASAO                                   0.0
CHIRANG                                      0.0
WEST KARBI ANGLONG                           0.0
BONGAIGAON                                   0.0
BAKSA                                   290500.0
HAILAKANDI                             1499700.0
SOUTH SALMARA MANCACHAR                1905000.0
KAMRUP METRO                           9112000.0
MAJULI                                39900000.0
KARIMGANJ                             44012500.0
KAMRUP                                44578520.0
GOALPARA                              63736509.0
UDALGURI                              64720805.0
NALBARI                               73701100.0
JORHAT                                77261200.0
GOLAGHAT                              79822000.0
HOJAI                                 82782961.0
SONITPUR                             106203700.0
CHARAIDEO                            124706000.0
MORIGAON                             161488300.0
DARRANG                              169452168.0
CACHAR                               193286453.0
BISWANATH                            229728200.0
NAGAON                               269277000.0
TINSUKIA                             304304000.0
DHEMAJI                              311851207.0
DHUBRI                               335242358.0
BARPETA                              452217530.0
DIBRUGARH                            514021000.0
KOKRAJHAR                            542781900.0

### Top 5 at risk 2024-2025

In [13]:
risk = pd.read_csv(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\Deployment\IDS-DRR-Himachal-Pradesh-Risk-Score-Model\RiskScoreModel\data\risk_score_final_district.csv')
risk_dist = risk.loc[risk['tehsil'].isnull()]
fy_2024 = ['2024_04','2024_05','2024_06','2024_07','2024_08','2024_09','2024_10','2024_11','2024_12','2025_01','2025_02','2025_03']
risk_2024_25 = risk_dist.loc[risk_dist['timeperiod'].isin(fy_2024)]
risk_2022_23 = risk_dist.loc[risk_dist['financial-year']=='2023-2024']
risk_2022_23

,object-id,district,timeperiod,total-tender-awarded-value,repair-and-restoration-tenders-awarded-value,lwss-tenders-awarded-value,ndrf-tenders-awarded-value,sdmf-tenders-awarded-value,wss-tenders-awarded-value,restoration-measures-tenders-awarded-value,...,ndrf-tenders-awarded-value-fy-cumsum,sdmf-tenders-awarded-value-fy-cumsum,wss-tenders-awarded-value-fy-cumsum,preparedness-measures-tenders-awarded-value-fy-cumsum,immediate-measures-tenders-awarded-value-fy-cumsum,others-tenders-awarded-value-fy-cumsum,relief-and-mitigation-sanction-value-fy-cumsum,topsis-score,risk-score,total-infrastructure-damage
5064,02-030,BILASPUR,2023_04,9154309.0,0.0,0.0,0.0,0.0,0.0,6503229.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.606295,4,0.0
5065,02-030,BILASPUR,2023_05,5001908.0,2619248.0,0.0,0.0,0.0,0.0,2382660.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.616198,4,0.0
5066,02-030,BILASPUR,2023_06,182446724.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.607542,4,0.0
5067,02-030,BILASPUR,2023_07,2231376.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.614939,4,0.0
5068,02-030,BILASPUR,2023_08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.647121,4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5566,02-029,UNA,2023_11,3026859.0,0.0,0.0,0.0,0.0,0.0,3026859.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.700384,5,0.0
5567,02-029,UNA,2023_12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.674088,5,0.0
5568,02-029,UNA,2024_01,3822000.0,3822000.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.628237,4,0.0
5569,02-029,UNA,2024_02,816931.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.643703,5,0.0
5570,02-029,UNA,2024_03,4150110.0,0.0,0.0,0.0,0.0,0.0,4150110.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.664129,4,0.0

In [14]:
dist_risk_2223 = risk_2022_23.groupby('district').agg({'topsis-score':'mean'}).reset_index()
dist_sort_2223 = dist_risk_2223.sort_values(by='topsis-score', ascending=False)
dist_sort_2223

          district  topsis-score
11             UNA      0.653194
9          SIRMAUR      0.624596
0         BILASPUR      0.620833
2         HAMIRPUR      0.603355
3           KANGRA      0.601403
10           SOLAN      0.599013
7            MANDI      0.582706
1           CHAMBA      0.570777
8           SHIMLA      0.519250
5            KULLU      0.413518
4          KINNAUR      0.317928
6   LAHAUL & SPITI      0.287450

In [15]:
dist_risk_2425 = risk_2024_25.groupby('district').agg({'topsis-score':'mean'}).reset_index()
dist_sort = dist_risk_2425.sort_values(by='topsis-score', ascending=False)
dist_sort

          district  topsis-score
11             UNA      0.651472
9          SIRMAUR      0.627953
0         BILASPUR      0.613483
3           KANGRA      0.605208
2         HAMIRPUR      0.603407
7            MANDI      0.598927
10           SOLAN      0.597790
1           CHAMBA      0.558697
8           SHIMLA      0.528704
5            KULLU      0.406380
4          KINNAUR      0.307587
6   LAHAUL & SPITI      0.265045

In [16]:
top10_list = dist_sort['district'].head(10).tolist()
print("Top 10 districts in dist_sort:", top10_list)

Top 10 districts in dist_sort: ['UNA', 'SIRMAUR', 'BILASPUR', 'KANGRA', 'HAMIRPUR', 'MANDI', 'SOLAN', 'CHAMBA', 'SHIMLA', 'KULLU']

In [17]:
dist_vul_2425 = risk_2024_25.groupby('district').agg({'vulnerability':'mean'}).reset_index()
dist_vul = dist_vul_2425.sort_values(by='vulnerability', ascending=False)
dist_vul

          district  vulnerability
1           CHAMBA            5.0
7            MANDI            5.0
9          SIRMAUR            5.0
0         BILASPUR            4.0
2         HAMIRPUR            4.0
4          KINNAUR            4.0
6   LAHAUL & SPITI            4.0
8           SHIMLA            4.0
3           KANGRA            3.0
5            KULLU            3.0
10           SOLAN            3.0
11             UNA            3.0

In [ ]:
# Ranking by vulnerability
vul = pd.read_csv(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\Deployment\IDS-DRR-Assam-Risk-Model\RiskScoreModel\data\factor_scores_l1_vulnerability.csv')
vul_fy24 = vul.loc[vul['timeperiod'].isin(fy_2024)]
vul_dist = vul_fy24.groupby(['district']).mean('landd_score').reset_index()
vul_dist = vul_dist.sort_values(by='landd_score', ascending=False)
vul_dist

,district,rc_area,total_tender_awarded_value,SOPD_tenders_awarded_value,SDRF_sanctions_awarded_value,SDRF_tenders_awarded_value,RIDF_tenders_awarded_value,LTIF_tenders_awarded_value,CIDF_tenders_awarded_value,Preparedness Measures_tenders_awarded_value,...,avg_electricity,avg_tele,rc_piped_hhds_pct,rc_nosanitation_hhds_pct,total_hhd,distance_from_river,drainage_density,efficiency,vulnerability,landd_score
6,CHARAIDEO,357.666667,9.026353e+05,9.026353e+05,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,8.624159,2.000000,3.802528,19.713480,36078.333333,4700.953196,0.000603,0.865896,3.000000,1.064854
24,MAJULI,485.000000,5.106683e+07,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,9.350751,2.500000,4.953339,17.280869,19619.500000,1292.455559,0.000625,0.892194,2.333333,1.053512
21,KARIMGANJ,367.800000,1.273939e+06,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,9.769837,2.400000,5.566885,14.247125,51232.200000,4060.318063,0.000533,0.959178,1.533333,1.047542
5,CACHAR,756.600000,2.825410e+06,0.000000e+00,0.0,0.0,1.857672e+06,0.0,0.0,0.0,...,9.771465,2.200000,8.534447,15.871015,83220.200000,3222.517656,0.000441,0.853619,3.000000,1.035562
9,DHEMAJI,413.833333,4.755809e+06,2.499565e+06,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,7.045081,2.000000,2.257948,20.872455,32504.166667,2238.641533,0.000553,0.827450,3.500000,1.034918
13,GOALPARA,395.800000,9.122372e+06,1.296579e+06,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,8.904281,2.000000,3.554577,25.416326,48091.800000,3585.306932,0.000571,0.847237,3.111111,1.033781
3,BISWANATH,594.333333,2.212126e+07,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,8.895602,2.333333,4.204080,28.459534,50312.666667,4363.593881,0.000613,0.805915,3.888889,1.033502
26,NAGAON,366.285714,3.407232e+06,6.906902e+05,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,9.826001,2.000000,4.975220,23.507534,75346.714286,3477.530108,0.000575,0.874396,2.841270,1.030543
10,DHUBRI,222.428571,1.963771e+06,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,7.527789,2.571429,1.185372,25.006394,53958.571429,2231.599333,0.000652,0.898141,2.380952,1.028673
15,HAILAKANDI,332.250000,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,9.485312,2.000000,4.009654,19.261827,41446.000000,4335.474967,0.000502,0.939078,1.833333,1.026444
28,SIVASAGAR,391.750000,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,10.377993,2.250000,6.810653,8.956793,43024.000000,3889.606733,0.000606,0.865492,2.944444,1.026141
14,GOLAGHAT,587.166667,2.757417e+05,0.000000e+00,0.0,0.0,2.757417e+05,0.0,0.0,0.0,...,8.803320,2.333333,7.175812,15.059643,45973.500000,3445.526863,0.000585,0.853150,3.018519,1.024651
0,BAJALI,156.666667,5.622576e+06,5.533235e+05,0.0,0.0,5.069252e+06,0.0,0.0,0.0,...,6.986936,2.333333,6.032021,9.753040,25965.000000,1123.703703,0.000681,0.971237,1.444444,1.024095
4,BONGAIGAON,217.600000,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,9.117916,2.200000,2.037956,12.861615,37082.800000,1883.330084,0.000580,0.868923,2.933333,1.022802
32,TINSUKIA,952.500000,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,8.609901,2.000000,3.415357,24.888151,79638.750000,4159.102888,0.000574,0.802389,3.861111,1.022534
2,BARPETA,308.000000,3.722496e+06,5.796883e+05,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,8.022187,2.000000,2.252056,15.041839,65563.000000,1247.611751,0.000646,0.859752,3.166667,1.022151
11,DIBRUGARH,482.714286,1.248564e+07,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,10.218744,2.000000,4.188471,12.796375,44503.285714,9491.630140,0.000625,0.817359,3.666667,1.021685
25,MORIGAON,302.400000,3.771459e+07,0.000000e+00,0.0,0.0,1.444280e+07,0.0,0.0,0.0,...,7.182747,2.400000,3.349935,15.812297,53555.600000,2700.336577,0.000598,0.789093,4.355556,1.016760
27,NALBARI,129.500000,5.893556e+06,6.697896e+05,0.0,0.0,1.454108e+06,0.0,0.0,0.0,...,10.468786,2.125000,9.660274,21.254124,29159.750000,1829.807307,0.000671,0.951594,1.680556,1.013261
18,KAMRUP,252.538462,2.910419e+05,1.397265e+05,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,10.062466,2.384615,3.324496,9.479860,31394.769231,4254.719948,0.000586,0.930375,2.017094,1.013050
22,KOKRAJHAR,391.375000,1.498432e+06,5.276989e+05,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,8.966230,2.250000,2.847452,22.904114,26863.000000,4296.624151,0.000562,0.885130,2.666667,1.009368
16,HOJAI,485.333333,3.262126e+06,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,8.001279,2.333333,5.274652,27.656618,71622.000000,5163.443601,0.000580,0.775525,4.444444,1.009340
8,DARRANG,322.200000,4.611035e+06,0.000000e+00,0.0,0.0,3.984459e+06,0.0,0.0,0.0,...,9.187852,2.000000,5.102351,12.999366,46371.800000,1098.834445,0.000672,0.841667,3.466667,1.008308
23,LAKHIMPUR,428.285714,3.386339e+06,0.000000e+00,0.0,0.0,1.417133e+06,0.0,0.0,0.0,...,8.319633,2.428571,2.831755,16.318743,38132.571429,2711.046414,0.000611,0.798868,4.000000,1.008065
29,SONITPUR,861.250000,1.262659e+06,4.720380e+05,0.0,0.0,2.360879e+05,0.0,0.0,0.0,...,9.790315,2.250000,6.036012,13.190631,79682.500000,1557.360655,0.000571,0.817134,3.722222,1.007445
17,JORHAT,373.000000,2.271386e+06,0.000000e+00,0.0,0.0,1.980110e+06,0.0,0.0,0.0,...,10.292051,2.200000,14.251304,12.066467,54541.400000,7133.757645,0.000604,0.914849,2.177778,1.007148
31,TAMULPUR,175.400000,4.394989e+06,1.699771e+05,0.0,0.0,2.027210e+06,0.0,0.0,0.0,...,11.551837,2.200000,5.783974,12.150416,22538.000000,1578.254040,0.000664,0.857079,3.133333,1.002474
33,UDALGURI,220.777778,2.693464e+06,1.304674e+05,0.0,0.0,8.882200e+05,0.0,0.0,0.0,...,8.335556,2.222222,3.074386,15.958328,20637.666667,1489.926404,0.000629,0.805861,3.790123,1.002228
20,KARBI ANGLONG,2445.666667,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,7.161017,2.000000,1.954752,23.466274,34377.000000,8511.666927,0.000410,0.934093,1.888889,1.000875
7,CHIRANG,385.200000,6.017778e+05,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,8.241345,2.200000,1.027828,25.348485,21089.000000,975.240792,0.000528,0.883840,2.711111,1.000693
1,BAKSA,218.000000,5.885898e+06,1.187141e+05,0.0,0.0,2.295287e+06,0.0,0.0,0.0,...,8.984337,2.285714,2.801875,15.460337,18886.142857,1576.549988,0.000591,0.829814,3.380952,1.000055
19,KAMRUP METRO,208.500000,2.941210e+07,5.857263e+06,0.0,0.0,5.980498e+06,0.0,0.0,0.0,...,12.073559,2.500000,11.460341,11.610285,81805.250000,3333.953707,0.000449,1.000000,1.000000,1.000000
12,DIMA HASAO,1221.000000,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,8.147461,2.500000,6.363166,23.250179,7529.750000,4923.297486,0.000313,0.989837,1.166667,1.000000
30,SOUTH SALMARA MANCACHAR,342.000000,1.470587e+06,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,6.664985,2.000000,3.569057,28.086322,101269.000000,880.805633,0.000585,0.886851,2.666667,1.000000
34,WEST KARBI ANGLONG,3073.000000,1.724642e+07,0.000000e+00,0.0,0.0,1.398523e+07,0.0,0.0,0.0,...,5.848965,2.000000,0.242649,28.835094,52339.000000,4989.532823,0.000439,0.780362,4.333333,1.000000

In [9]:
expenses = pd.read_csv(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\Deployment\flood-data-ecosystem-Assam\Sources\SDRF\data\flood_expenses_RCgeotagged.csv')
fy_expenses = ['2024-25']
expenses_fy24 = expenses.loc[expenses['Financial Year'].isin(fy_expenses)] 
expenses_fy24

,Unnamed: 0,Name of the Scheme,Whether scheme,Whether the scheme is funded by NABARD,Proposal Number,Proposal Date,Issued Number,Valid Upto,Admin Department File Number,Brief nature of the scheme,...,tender_district_title_description,tender_district_location,DISTRICT_FINALISED,tender_villages,tender_block,tender_subdistrict,tender_revenueci,tender_revenueci_location,HQ_flag,REVENUE_CIRCLE_FINALISED
84,6215,Immediate measures to flood protection & drain...,Ongoing Project(Parent Proposal No. AA-05-2018...,NaN,NaN,26-07-2024,NaN,NaN,NaN,NaN,...,KARIMGANJ,KARIMGANJ,KARIMGANJ,"PATHARKANDI,Patharkandi",RAMKRISHNA NAGAR,Patharkandi,Patharkandi,Karimganj,True,Karimganj
85,6291,Restoration of road from Kanaibazar- Anipur PW...,Ongoing Project(Parent Proposal No. AA-05-2014...,NaN,NaN,13-11-2024,NaN,NaN,-N/A-,-N/A-,...,NaN,KARIMGANJ,KARIMGANJ,"ANIPUR,KANAIBAZAR",PATHARKANDI,Badarpur,Nilambazar,Karimganj,True,Karimganj
251,6245,Strengthening of the road from Thikadarbasti t...,New project,No,AA-05-2024-25-7313,02-09-2024,AA/05_2024-25(I)_5587,02-09-2029,496063,Mitigation Scheme,...,HOJAI,HOJAI,HOJAI,"THIKADARBASTI,ThikadarBasti,DOBOKA",JUGIJAN,Doboka,Doboka,Hojai,True,Hojai
260,6323,Immediate measures to restore breach like dama...,Ongoing Project(Parent Proposal No. AA-05-2024...,NaN,NaN,04-03-2025,NaN,NaN,-N/A-,-N/A-,...,WEST KARBI ANGLONG,NaN,WEST KARBI ANGLONG,NaN,NaN,NaN,NaN,NaN,False,NaN
650,6139,Temporary Restoration of Rangia-Hajo Road at S...,New project,No,AA-05-2024-25-7205,30-07-2024,AA/05_2024-25(I)_5567,13-08-2027,296030,FDR,...,KAMRUP,NaN,KAMRUP,Simalua,RANGIA,Hajo,Hajo,NaN,False,Hajo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6379,6372,Repair/Renovation of Circle Office building in...,Ongoing Project(Parent Proposal No. AA-05-2021...,NaN,NaN,30-10-2024,NaN,NaN,-N/A-,-N/A-,...,DIBRUGARH,KAMRUP METRO,CONFLICT,NaN,NaN,NaN,NaN,NaN,False,NaN
6380,6375,Repairing / renovation work of the office buil...,Ongoing Project(Parent Proposal No. AA-05-2021...,NaN,NaN,19-12-2024,NaN,NaN,-N/A-,-N/A-,...,KARIMGANJ,KAMRUP METRO,CONFLICT,NaN,NaN,NaN,NaN,NaN,False,NaN
6381,6376,Repairing and Renovation of Circle Office buil...,Ongoing Project(Parent Proposal No. AA-05-2020...,NaN,NaN,19-12-2024,NaN,NaN,-N/A-,-N/A-,...,GOALPARA,KAMRUP METRO,CONFLICT,NaN,NaN,NaN,NaN,NaN,False,NaN
6382,6377,Construction of Circle Office building includi...,Ongoing Project(Parent Proposal No. AA-LRS-201...,NaN,NaN,07-01-2025,NaN,NaN,-N/A-,-N/A-,...,DIBRUGARH,KAMRUP METRO,CONFLICT,NaN,NaN,NaN,NaN,NaN,False,NaN
6383,6378,Construction of Silchar Sadar Revenue Circle O...,Ongoing Project(Parent Proposal No. AA-05-2021...,NaN,NaN,16-01-2025,NaN,NaN,-N/A-,-N/A-,...,CACHAR,KAMRUP METRO,CONFLICT,NaN,NaN,NaN,NaN,NaN,False,NaN

In [10]:
# Identifying the top 10 districts with the highest administrative approval amount
dist_fy24 = expenses_fy24.groupby(['DISTRICT_FINALISED']).agg({'Total Administrative Approval Amount In Lakhs':'sum'}).reset_index()
dist_fy24_sorted = dist_fy24.sort_values(by='Total Administrative Approval Amount In Lakhs', ascending=False)
dist_fy24_sorted

    DISTRICT_FINALISED  Total Administrative Approval Amount In Lakhs
15        KAMRUP METRO                                     4518.14092
14              KAMRUP                                     2917.14534
10            GOLAGHAT                                     1926.78000
5             CONFLICT                                     1392.71539
19            SIVSAGAR                                      927.14000
11               HOJAI                                      674.06461
6              DHEMAJI                                      503.98200
21            UDALGURI                                      480.36900
17              NAGAON                                      302.50000
20            SONITPUR                                      223.01300
7               DHUBRI                                       97.18353
0               BAJALI                                       47.49000
18             NALBARI                                       35.24191
9             GOALPARA                                       31.57000
8            DIBRUGARH                                       28.44000
4           BONGAIGAON                                       18.91000
2              BARPETA                                        8.50000
1                BAKSA                                        2.90500
12              JORHAT                                        0.00000
13           K.ANGLONG                                        0.00000
16           KARIMGANJ                                        0.00000
3            BISWANATH                                        0.00000
22  WEST KARBI ANGLONG                                        0.00000

In [14]:
## Identifying the highest value expenses

expenses_fy24_sorted = expenses_fy24.sort_values(by='Total Administrative Approval Amount In Lakhs', ascending=False)
expenses_fy24_sorted.head(20)

,Unnamed: 0,Name of the Scheme,Whether scheme,Whether the scheme is funded by NABARD,Proposal Number,Proposal Date,Issued Number,Valid Upto,Admin Department File Number,Brief nature of the scheme,...,tender_district_title_description,tender_district_location,DISTRICT_FINALISED,tender_villages,tender_block,tender_subdistrict,tender_revenueci,tender_revenueci_location,HQ_flag,REVENUE_CIRCLE_FINALISED
1842,6381,Procurement of Machinery and Trolley Mounted P...,New project,No,AA-SDM-2024-25-0007,20-01-2025,AA/SDM_2024-25(I)_03,29-01-2030,499824,Procurement of Machinery and Trolley Mounted P...,...,KAMRUP METRO,NaN,KAMRUP METRO,NaN,NaN,Guwahati,Guwahati,NaN,False,Guwahati
653,6289,Improvement of road from Boko to Upper Lumpi (...,New project,No,AA-05-2024-25-7351,28-10-2024,AA/05_2024-25(I)_5627,05-11-2029,461420,Mitigation scheme,...,KAMRUP,NaN,KAMRUP,NaN,BOKO,Boko,Boko,NaN,False,Boko
654,6290,Improvement of road from Boko to Upper Lumpi (...,New project,No,AA-05-2024-25-7351,28-10-2024,AA/05_2024-25(I)_5627,05-11-2029,461420,Mitigation scheme,...,KAMRUP,NaN,KAMRUP,NaN,BOKO,Boko,Boko,NaN,False,Boko
1721,6298,Flood mitigation at Chowdangpathar area by dre...,New project,No,AA-05-2024-25-7414,11-02-2025,AA/05_2024-25(I)_5650,27-02-2030,574276,Mitigation Scheme,...,NaN,GOLAGHAT,GOLAGHAT,GHILADHARI,GOLAGHAT EAST,Golaghat,Golaghat,Golaghat,True,Golaghat
4446,6297,"Cleaning of Jamuna canal around Sivasagar, Bor...",New project,No,AA-05-2024-25-7413,11-02-2025,AA/05_2024-25(I)_5651,27-02-2030,574276,Mitigation Scheme,...,SIVSAGAR,SIVSAGAR,SIVSAGAR,NaN,SIVASAGAR,Dimow,Dimow,Sibsagar,True,Sibsagar
1834,6361,Designing Scientific Land Valuation Framework ...,New project,No,AA-LRS-2024-25-7325,30-09-2024,AA/LRS_2024-25(I)_5501,18-11-2029,532720,Implementation of Scientific Land Valuation Fr...,...,NaN,KAMRUP METRO,KAMRUP METRO,NaN,NaN,NaN,NaN,NaN,False,NaN
251,6245,Strengthening of the road from Thikadarbasti t...,New project,No,AA-05-2024-25-7313,02-09-2024,AA/05_2024-25(I)_5587,02-09-2029,496063,Mitigation Scheme,...,HOJAI,HOJAI,HOJAI,"THIKADARBASTI,ThikadarBasti,DOBOKA",JUGIJAN,Doboka,Doboka,Hojai,True,Hojai
5973,6316,Supply and Installation of Solar Powered Mobil...,New project,No,AA-05-2024-25-7439,13-02-2025,AA/05_2024-25(I)_5634,27-02-2028,574276,Mitigation scheme,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
5972,6315,Supply and Installation of Solar Powered Mobil...,New project,No,AA-05-2024-25-7439,13-02-2025,AA/05_2024-25(I)_5634,27-02-2028,574276,Mitigation scheme,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
1564,6383,Resilient Relief Camp on Wheels in 02 flood pr...,New project,No,AA-SDM-2024-25-0009,25-02-2025,AA/SDM_2024-25(I)_05,13-03-2028,231771,Resilient Relief Camp on Wheels in 02 flood pr...,...,NAGAON,NaN,NAGAON,NaN,NaN,Nagaon,Nagaon,NaN,False,Nagaon
4838,6306,Re-direction of stream to its original course ...,New project,No,AA-05-2024-25-7422,11-02-2025,AA/05_2024-25(I)_5643,27-02-2028,574276,Mitigation Scheme,...,NaN,DHEMAJI,DHEMAJI,NaN,NaN,NaN,NaN,Dhemaji,True,Dhemaji
1722,6299,Dhansiri river bank Anti Erosion Project at Dh...,New project,No,AA-05-2024-25-7415,11-02-2025,AA/05_2024-25(I)_5649,27-02-2028,574276,Mitigation Scheme,...,GOLAGHAT,GOLAGHAT,GOLAGHAT,"DHANSIRIPAR,Dhansiripar,GOLAGHAT",GOLAGHAT WEST,Golaghat,Golaghat,Golaghat,True,Golaghat
1723,6300,Gelabill River Bank Anti Erosion Project at Ka...,New project,No,AA-05-2024-25-7416,11-02-2025,AA/05_2024-25(I)_5648,27-02-2028,574276,Mitigation Scheme,...,NaN,GOLAGHAT,GOLAGHAT,NaN,NaN,NaN,NaN,Golaghat,True,Golaghat
5938,6125,Mitigation of flash flood to reducing sediment...,New project,No,AA-05-2024-25-7192,19-06-2024,AA/05_2024-25(I)_5478,24-06-2027,403105,Mitigation scheme,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
5971,6304,Mitigation of pluvial flood and erosion at Utt...,New project,No,AA-05-2024-25-7420,11-02-2025,AA/05_2024-25(I)_5645,27-02-2028,574276,Mitigation Scheme,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
5955,6276,Protective measures for the Maloibari ELIS for...,New project,No,AA-05-2024-25-7344,28-10-2024,AA/05_2024-25(I)_5620,02-11-2027,500240,SDMF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
1725,6302,Doigurung river Bank Anti Erosion project at P...,New project,No,AA-05-2024-25-7418,11-02-2025,AA/05_2024-25(I)_5646,27-02-2028,574276,Mitigation Scheme,...,NaN,GOLAGHAT,GOLAGHAT,NaN,NaN,NaN,NaN,Golaghat,True,Golaghat
4191,6303,Gahigaon Water Harvesting cum water Distributi...,New project,No,AA-05-2024-25-7419,11-02-2025,AA/05_2024-25(I)_5655,28-02-2028,574276,Mitigation Scheme,...,NaN,SONITPUR,SONITPUR,NaN,NaN,NaN,NaN,NaN,False,NaN
5939,6127,Mitigation of flash flood to reducing sediment...,New project,No,AA-05-2024-25-7194,19-06-2024,AA/05_2024-25(I)_5477,24-06-2027,403105,Mitigation Scheme,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
6358,6265,RCC Drain from Ghilamara Tiniali to North Bank...,New project,No,AA-05-2024-25-7334,08-10-2024,AA/05_2024-25(I)_5616,02-11-2027,496057,mitigation scheme,...,CACHAR,KARIMGANJ,CONFLICT,NaN,NaN,NaN,NaN,NaN,False,NaN

In [ ]:
exp_22_23 = expenses.loc[expenses['Financial Year']=='2022-23']
exp_22_23_march = exp_22_23.loc[exp_22_23['Month']=='March']

In [16]:
golaghat_24 = expenses_fy24_sorted.head(20).loc[expenses_fy24_sorted['DISTRICT_FINALISED']=='GOLAGHAT']
golaghat_24

,Unnamed: 0,Name of the Scheme,Whether scheme,Whether the scheme is funded by NABARD,Proposal Number,Proposal Date,Issued Number,Valid Upto,Admin Department File Number,Brief nature of the scheme,...,tender_district_title_description,tender_district_location,DISTRICT_FINALISED,tender_villages,tender_block,tender_subdistrict,tender_revenueci,tender_revenueci_location,HQ_flag,REVENUE_CIRCLE_FINALISED
1721,6298,Flood mitigation at Chowdangpathar area by dre...,New project,No,AA-05-2024-25-7414,11-02-2025,AA/05_2024-25(I)_5650,27-02-2030,574276,Mitigation Scheme,...,NaN,GOLAGHAT,GOLAGHAT,GHILADHARI,GOLAGHAT EAST,Golaghat,Golaghat,Golaghat,True,Golaghat
1722,6299,Dhansiri river bank Anti Erosion Project at Dh...,New project,No,AA-05-2024-25-7415,11-02-2025,AA/05_2024-25(I)_5649,27-02-2028,574276,Mitigation Scheme,...,GOLAGHAT,GOLAGHAT,GOLAGHAT,"DHANSIRIPAR,Dhansiripar,GOLAGHAT",GOLAGHAT WEST,Golaghat,Golaghat,Golaghat,True,Golaghat
1723,6300,Gelabill River Bank Anti Erosion Project at Ka...,New project,No,AA-05-2024-25-7416,11-02-2025,AA/05_2024-25(I)_5648,27-02-2028,574276,Mitigation Scheme,...,NaN,GOLAGHAT,GOLAGHAT,NaN,NaN,NaN,NaN,Golaghat,True,Golaghat
1725,6302,Doigurung river Bank Anti Erosion project at P...,New project,No,AA-05-2024-25-7418,11-02-2025,AA/05_2024-25(I)_5646,27-02-2028,574276,Mitigation Scheme,...,NaN,GOLAGHAT,GOLAGHAT,NaN,NaN,NaN,NaN,Golaghat,True,Golaghat

In [38]:
# Select top 10 districts from dist_sort based on the risk score.
top10 = dist_sort.head(10)

# Merge the top 10 districts with the funds dataframe.
# We assume that the 'district' column from dist_sort corresponds to 'DISTRICT_FINALISED' in dist_fy25_sorted.
top10_funds = pd.merge(top10, dist_fy25_sorted, left_on='district', right_on='DISTRICT_FINALISED', how='left')

# Sum the funds disbursed to the top 10 districts.
top10_total_funds = top10_funds['Total Administrative Approval Amount In Lakhs'].sum()

# Calculate the total funds disbursed across all districts.
total_funds = dist_fy25_sorted['Total Administrative Approval Amount In Lakhs'].sum()

# Compute the proportion.
proportion = top10_total_funds / total_funds

print("Proportion of funds received by the top 10 districts:", proportion)

Proportion of funds received by the top 10 districts: 0.009488021324028432